# Generated by Django 2.2.24 on 2024-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='level_of_study',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='school',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
